apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: walter-service
    spec:
      type: ClusterIP
      selector:
        service: walter
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: walter
    spec:
      replicas: 1
      selector:
        matchLabels:
          service: walter
      template:
        metadata:
          labels:
            service: walter
        spec:
          containers:
            - name: walter
              image: walter
kind: List
metadata: {}